[project]
name = "gdsi-elo-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.42.2",
]

[dependency-groups]
dev = [
    "pyright>=1.1.396",
]
